server:
  port: 8080

spring:
  application:
    name: project-webapp
  datasource:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456
  jpa:
    open-in-view: false
    show-sql: true

mybatis:
  type-aliases-package: 'com.whyischen.projectwebapp.entity'

logging:
  level:
    org.zalando.logbook: trace

logbook:
  format:
    style: http
